export const LOGIN_USER = 'ACT_LOGIN'
export const LOGOUT_USER = 'ACT_LOGOUT'
export const SELECT_SURVEY = 'ACT_USER_SELECT_SURVEY_WITH_SELECT_ID'
export const DESELECT_SURVEY = 'ACT_USER_GOING_BACK'
export const ADD_MAIN_DATA ='ACT_MAIN_DATA'

export const ADD_CORPS_LIST = 'ACT_ADD_CORP_LIST'
export const ADD_ETHINICITY_LIST = 'ACT_ADD_ETHINIC_LIST'
export const ADD_AREA_TYPE_LIST = 'ACT_AREA_TYPE_LIST'
export const ADD_METHOD_TYPE_LIST = 'ACT_METHOD_TYPE_LIST'

export const EMPTY_MAIN_DATA = 'ACT_SUCESSFULLY_SUMBITTED_ALL_DATA'




